### ISSUE TITLE
3d Secure enabled Credit Card payments are failing.

### ISSUE THREAD

**Issue by heilapom** [pfpayments/magento-2#11]
3d secure enabled Credit Card payments are failing because checkout.postfinance.ch host is not in CSP whitelist's connect-src policy.

Content Security Policy: The page’s settings blocked the loading of a resource at https://checkout.postfinance.ch/s/17995/payment/endeavour-3dsecure-v2/update/5563945/1670938260673-SCUVS1SCZZz_KFPgCy1HpxgPxgafiMah7vKtOadBXW8-1531299535039 (“connect-src”). [challenge.js:33:7]

**Comment by theodorspringwallee** [comment]
Dear [heilapom](https://github.com/heilapom)

In general, we can't confirm that the 3D-Secure process is failing.

We assume that this issue is related to your specific case.

For this please contact the PostFinance support: https://www.postfinance.ch/en/support/hotline.html

Best regards
