### ISSUE TITLE
Not able to cancel invoice

### ISSUE THREAD

**Issue by sunilit42** [pfpayments/magento-2#14]
![image](https://user-images.githubusercontent.com/2923438/236643846-766c85b6-1ef1-482b-87a9-1c91b02b9561.png)

![image](https://user-images.githubusercontent.com/2923438/236643885-e01899e4-9059-4a7d-aa46-18062a71137e.png)

I m trying to cancel order from magento side , but not able to do it

**Comment by theodorspringwallee** [comment]
Dear [sunilit42](https://github.com/sunilit42)

Please get in touch with info@wallee.com and provide there your space ID and further requested data.

Best regards
