### ISSUE TITLE
Link broken in Readme

### ISSUE THREAD

**Issue by Crissov** [pfpayments/magento-2#2]
The links to <https://www.postfinance.ch/checkout/> in `README.md` do not work (anymore). You probably want to point users to something like <https://www.postfinance.ch/en/business/products/e-commerce.html> instead.

**Comment by theodorspringwallee** [comment]
Dear [Crissov](https://github.com/Crissov)

Thank you for your request. 

We adjusted the readme link to the specific product on the PostFinance site: https://www.postfinance.ch/en/business/products/e-commerce/postfinance-checkout-all-in-one.html 

Therefore, this request will be closed.
