### ISSUE TITLE
Magento 2.4.4 setup upgrade error

### ISSUE THREAD

**Issue by bondazzi** [pfpayments/magento-2#6]
I'm trying to install the module on Magento 2.4.4 (or 2.4.4-p1) but during

bin/magento setup:upgrade

I have this error:

call_user_func(): Argument #1 ($callback) must be a valid callback, class "PostFinanceCheckout\Payment\Setup\Patch\Data\AddData" not found#0

Has the module the compatibility with Magento 2.4.4? Is there a solution for this error?

Thank you

**Comment by kess78** [comment]
The same happens on Magento 2.3.6-p1

**Comment by theodorspringwallee** [comment]
Dear [bondazzi](https://github.com/bondazzi), [kess78](https://github.com/kess78) this was I BUG, which should be fixed now.

Please delete our current plugin version completely from Magento 2 and reinstall the newest version.
